# This dictionary defines the entire macro flow.
# The MacroEngine will execute states and actions in order.
#
# States: A logical grouping of actions (e.g., 'TUTORIAL', 'ACCOUNT_RESET').
#
# Actions: A dictionary describing what to do.
#   - 'action': The name of the action for the engine to execute.
#   - 'params': A dictionary of parameters for that action.
#   - 'comment': A description of the action.
#   - 'optional': If True, the engine will continue even if this action fails.

MACRO_FLOW = {
    "INITIAL_SETUP": [
        {'action': 'Image_Click', 'params': {'wait_image': 'app_icon'}, 'comment': 'Launch app'},
        {'action': 'Image_Click', 'params': {'wait_image': 'title_start'}, 'comment': 'Click start button on title screen', 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'title_start'}, 'comment': 'Retry click start button'},
        {'action': 'Image_Click', 'params': {'wait_image': 'guest_login'}, 'comment': 'Click guest login'},
    ],
    "TUTORIAL_PART_1": [
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'first_cutscean', 'click_image': 'cutscene_skip'}, 'comment': 'Skip first cutscene (optional)', 'optional': True},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'cutscene_skip'}, 'comment': 'Skip cutscene'},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_1'}, 'comment': 'Tutorial dialog 1-4'},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_2'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_3'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_4'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_action_1'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_5', 'click_image': 'tuto_action_2'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_6', 'click_image': 'tuto_action_3'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_7', 'click_image': 'battle_confirm_button'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_8'}, 'comment': 'Tutorial dialog 8-9'},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_9'}},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'cutscene_skip'}, 'comment': 'Skip cutscene'},
    ],
    "TUTORIAL_PART_2": [
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_10'}, 'comment': 'Tutorial dialog 10-17'},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_11'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_12'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_13'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_14'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_15'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_16'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_17', 'click_image': 'tuto_action_5'}, 'comment': 'Tutorial actions 5-8'},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_action_6', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_action_7'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_action_8'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'battle_confirm_button', 'wait_time': 5}},
    ],
    "TUTORIAL_PART_3": [
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_18'}, 'comment': 'Tutorial dialog 18-27'},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_19'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_20'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_21'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_22', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_23'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_24'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_25'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_26'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'tuto_dialog_27'}},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'cutscene_skip', 'wait_time': 5}, 'comment': 'Skip cutscene (x2)'},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'cutscene_skip', 'wait_time': 5}},
    ],
    "NICKNAME_CREATION": [
        {'action': 'Image_Click', 'params': {'wait_image': 'nickname_input_confirm'}, 'comment': 'Confirm nickname'},
        {'action': 'Image_Click', 'params': {'wait_image': 'nickname_creation_confirm', 'wait_time': 5}, 'comment': 'Confirm character creation'},
        {'action': 'Image_Click', 'params': {'wait_image': 'skip_after_creation'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'story_skip_confirm'}},
    ],
    "CHAPTER_1_1_PART_1": [
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_1'}, 'comment': 'Chapter 1-1 Dialogs'},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_2'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_3'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_4'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_5'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_6'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_7'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_8', 'click_image': '1-1_action_1'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_9', 'click_image': '1-1_action_2'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_10', 'click_image': 'battle_confirm_button'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_11'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_action_3'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'battle_confirm_button'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_12', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button', 'wait_time': 5}},
    ],
    "CHAPTER_1_1_PART_2": [
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_13'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_14'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_15'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_16'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_17'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_18'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_19'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_20', 'click_image': '1-1_action_4'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_21', 'click_image': '1-1_action_5'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_22', 'click_image': 'battle_confirm_button'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_23'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_24'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_25', 'click_image': '1-1_action_6'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_26'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_27', 'click_image': '1-1_action_13'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'battle_confirm_button', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_action_7'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'battle_confirm_button', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_action_8'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'battle_confirm_button', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_28', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button', 'wait_time': 5}, 'comment': 'Skip dialog (x2)'},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button', 'wait_time': 5}},
    ],
    "CHAPTER_1_1_PART_3": [
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_29'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_30'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_31'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_action_11', 'wait_time': 5}, 'comment': 'Click action (x2)'},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_action_11', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_32'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_33'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_action_11', 'wait_time': 5}, 'comment': 'Click action (x2)'},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_action_11', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_34'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_34'}, 'comment': 'Retry clicking dialog 34'},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_action_12'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_35'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-1_dialog_36', 'wait_time': 5}},
    ],
    "CHAPTER_1_1_COMPLETE": [
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'comment': 'Retry level up click'},
        {'action': 'Image_Click', 'params': {'wait_image': 'mission_complete'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'comment': 'Retry mission complete click'},
        {'action': 'Image_Click', 'params': {'wait_image': 'mission_complete'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'stage_clear_confirm'}},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'cutscene_skip', 'wait_time': 5}, 'comment': 'Skip cutscene (x3)'},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'cutscene_skip', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button'}},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'cutscene_skip', 'wait_time': 5}},
    ],
    "LOBBY_AND_CHAPTER_1_2_START": [
        {'action': 'Image_Click', 'params': {'wait_image': 'lobby_event_screen'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'lobby_preparation'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1st_stage_entry_confirm'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_stage_select'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'stage_entry'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button', 'wait_time': 5}},
    ],
    "CHAPTER_1_2_PART_1": [
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_1'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_2'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_3'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_4'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_5'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_6'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_7'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_8'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_9'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_10', 'click_image': '1-2_action_1'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_11', 'click_image': '1-2_action_2'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_12', 'click_image': '1-2_action_3'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_13', 'click_image': '1-2_action_2'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_14', 'click_image': '1-2_action_4'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_15', 'click_image': 'auto_stage', 'wait_time': 20}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-2_dialog_16', 'wait_time': 10}},
    ],
    "CHAPTER_1_2_COMPLETE": [
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'comment': 'Retry level up click'},
        {'action': 'Image_Click', 'params': {'wait_image': 'mission_complete'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'comment': 'Retry mission complete click'},
        {'action': 'Image_Click', 'params': {'wait_image': 'mission_complete'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'stage_clear_confirm_small'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button', 'wait_time': 5}},
    ],
    "CHAPTER_1_3_START": [
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_stage_select'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'stage_entry'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_1'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_2', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_3'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_4'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_5'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_6'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_7'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_action_1', 'wait_time': 7}},
        {'action': 'Click_Pos', 'params': {'x': 100, 'y': 450, 'wait_time': 8}},
        {'action': 'Image_Click', 'params': {'wait_image': 'auto_stage', 'wait_time': 15}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_8'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_action_3', 'wait_time': 5}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_action_3', 'wait_time': 5}, 'comment': 'Retry 1-3 action 3'},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_dialog_9'}},
    ],
    "CHAPTER_1_3_COMPLETE": [
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'comment': 'Retry level up click'},
        {'action': 'Image_Click', 'params': {'wait_image': 'mission_complete'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'comment': 'Retry mission complete click'},
        {'action': 'Image_Click', 'params': {'wait_image': 'mission_complete'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'stage_clear_confirm'}},
    ],
    "SIDE_STORY_AND_CHAPTER_1_4": [
        {'action': 'Image_Click', 'params': {'wait_image': 'sl-1-1_stage_select'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'story_stage_view'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'empty_area_touch'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-4_stage_select'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'stage_entry'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-4_dialog_1'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-4_dialog_2'}},
        {'action': 'Image_Click', 'params': {'wait_image': '1-3_action_1'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'auto_stage', 'wait_time': 25}},
    ],
    "CHAPTER_1_4_COMPLETE": [
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'comment': 'Retry level up click'},
        {'action': 'Image_Click', 'params': {'wait_image': 'mission_complete'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'level_up'}, 'comment': 'Retry mission complete click'},
        {'action': 'Image_Click', 'params': {'wait_image': 'mission_complete'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'stage_clear_confirm'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'sl-1-2_stage_select'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'story_stage_view'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'dialog_skip_button', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'empty_area_touch'}},
    ],
    "RECRUIT_TUTORIAL": [
        {'action': 'Image_Click', 'params': {'wait_image': 'recruit_dialog_1', 'click_image': 'lobby_button', 'wait_time': 10}},
        {'action': 'Image_Click', 'params': {'wait_image': 'empty_area_touch'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'recruit_dialog_2', 'click_image': 'recruit_button'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'empty_area_touch'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'recruit_dialog_2', 'click_image': 'recruit_button'}, 'comment': 'Retry recruit dialog 2'},
        {'action': 'Image_Click', 'params': {'wait_image': 'recruit_dialog_3', 'click_image': 'recruit_action_3'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'recruit_dialog_4', 'click_image': 'recruit_action_4'}},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'gacha_preview_skip', 'wait_time': 20}, 'optional': True},
        {'action': 'Click_Pos', 'params': {'x': 100, 'y': 400, 'wait_time': 20}, 'comment': 'Fallback for gacha skip'},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'gacha_result_close', 'wait_time': 5}, 'optional': True},
        {'action': 'Click_Pos', 'params': {'x': 100, 'y': 400, 'wait_time': 5}, 'comment': 'Fallback for gacha close'},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'gacha_result_close', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'recruit_dialog_5', 'click_image': 'lobby_button'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'lobby_button_other'}, 'comment': 'Fallback for lobby button'},
    ],
    "MAINTENANCE_TUTORIAL": [
        {'action': 'Image_Click', 'params': {'wait_image': 'recruit_dialog_6', 'click_image': 'maintenance_button'}},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'cutscene_skip', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'maintenance_tutorial_skip'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'lobby_button'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'lobby_button_other'}, 'comment': 'Fallback for lobby button'},
    ],
    "MAIL_REWARD": [
        {'action': 'Image_Click', 'params': {'wait_image': 'mail_button'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'mail_all_receive', 'wait_time': 15}},
        {'action': 'Click_Pos', 'params': {'x': 100, 'y': 450, 'wait_time': 5}},
        {'action': 'Pos_Click_Then_Image_Click', 'params': {'wait_image': 'empty_area_touch', 'wait_time': 5}, 'optional': True},
        {'action': 'Click_Pos', 'params': {'x': 100, 'y': 450, 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'empty_area_touch', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'back_button'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'back_button_other'}, 'comment': 'Fallback for back button'},
    ],
    "BEGINNER_GACHA": [
        {'action': 'Special_Command', 'params': {'command': 'repeat_beginner_gacha', 'count': 5}},
    ],
    "PICKUP_GACHA": [
        {'action': 'Image_Click', 'params': {'wait_image': 'recruit_button'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'gacha_shop'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'pickup_item_purchase'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'purchase_item_available'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'purchase_item_available'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'purchase_item_available'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'purchase_item_available'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'purchase_item_available'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'gacha_item_confirm'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'empty_area_touch'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'back_button'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'back_button_other'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'number_of_items'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'pickup_10_times', 'wait_time': 3}},
        {'action': 'Special_Command', 'params': {'command': 'app_restart'}},
    ],
    "CHECK_CHARACTERS": [
        {'action': 'Image_Click', 'params': {'wait_image': 'maintenance_button'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'maintenance_list_expand', 'wait_time': 5}},
        {'action': 'Special_Command', 'params': {'command': 'compare_and_branch', 'image1_name': 'suomi', 'image2_name': 'kyeongu', 'success_state': '__END__', 'fail_state': 'ACCOUNT_RESET'}},
    ],
    "ACCOUNT_RESET": [
        {'action': 'Image_Click', 'params': {'wait_image': 'lobby_button'}, 'optional': True},
        {'action': 'Image_Click', 'params': {'wait_image': 'lobby_button_other'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'guest_login_action_1', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'guest_login_action_2', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'guest_login_action_3', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'guest_login_action_4', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'guest_login_action_5', 'wait_time': 5}},
        {'action': 'Image_Click', 'params': {'wait_image': 'guest_login_action_6', 'wait_time': 5}},
        {'action': 'Input_Text', 'params': {'text': 'Delete'}},
        {'action': 'Image_Click', 'params': {'wait_image': 'guest_login_action_7', 'wait_time': 5}},
        {'action': 'Close_App', 'params': {}},
        {'action': 'Special_Command', 'params': {'command': '__RESTART__'}},
    ]
}